export default {
    LOGIN_ROUTE:"/login",
    LOGOUT_ROUTE:"/logout", 
    USERS_ROUTE:"/users",   
    USER_ID_ROUTE:"/user/:id",
    EDIT_USER_ID_ROUTE:"/user/edit/:id",
    BRANDS_ROUTE:"/brands", 
    BRAND_ID_ROUTE:"/brand/:id",
    EDIT_BRAND_ID_ROUTE:"/brand/edit/:id",
    PRODUCTS_ROUTE:"/products",
    PRODUCT_ID_ROUTE:"/product/:id",
    EDIT_PRODUCT_ID_ROUTE:"/product/edit/:id",   
    ORDERS_ROUTE:"/orders",
    ORDER_ID_ROUTE:"/order/:id",
    EDIT_ORDER_ID_ROUTE:"/order/edit/:id",
    PACKED_ORDER_ID_ROUTE:"/order/packed/:id",  
    SHIPPED_ORDER_ID_ROUTE:"/order/shipped/:id",
    DELIVERED_ORDER_ID_ROUTE:"/order/delivered/:id",
    RATINGS_ROUTE:"/ratings",
    RATING_ID_ROUTE:"/rating/:id",
    EDIT_RATING_ID_ROUTE:"/rating/edit/:id",
    CANCEL_ORDER_ROUTE: "/order/cancel/:id",
    APPROVE_CANCEL_ROUTE: "/order/cancel/approve/:id",  
    SEND_OTP_ROUTE:"/user/otp",
    CHANGE_PASSWORD_OTP_ROUTE:"/user/otp/password",  

}